using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
public class GameManager : MonoBehaviour
    {
        public static GameManager instance;

        [Header("References")]
        [SerializeField] private GameObject player_prefab;
        [SerializeField] private Transform[] face_slots;   
        [SerializeField] private GameObject[] indicators; 
        [SerializeField] private CameraFollow main_camera; 

        private List<Player> player_instances = new List<Player>();
        private Player active_player;
        private int current_player_index = 0;
        
        // This must match the name of the class generated by your Input Asset
        private InputSystem_Actions input_handler;

        void Awake()
        {
            if (instance == null) instance = this;
            else Destroy(gameObject);

            // Initialize the input handler
            input_handler = new InputSystem_Actions();
        }

        void Start()
        {
            // IMPORTANT: If you don't enable this, Move.ReadValue will stay (0,0)
            input_handler.Enable();

            SpawnAllPlayers();
            ActivateTurn(0);
        }

        void SpawnAllPlayers()
        {
            // Loops only as many times as you have slots assigned in the Inspector
            for (int i = 0; i < face_slots.Length; i++)
            {
                GameObject go = Instantiate(player_prefab, Vector3.zero, Quaternion.identity);
                Player p = go.GetComponent<Player>();

                if (p != null)
                {
                    p.SetupPlayer(this, face_slots[i]);
                    p.SetActiveState(false);
                    player_instances.Add(p);
                }
            }
        }

        void ActivateTurn(int index)
        {
            // Safety check to ensure we don't go out of bounds
            if (player_instances.Count == 0 || index >= player_instances.Count)
            {
                Debug.Log("All players finished or no players spawned!");
                return;
            }

            current_player_index = index;
            active_player = player_instances[index];
            active_player.SetActiveState(true);

            if (main_camera != null) 
                main_camera.target = active_player.transform;

            // Re-bind the Interaction event
            input_handler.Player.Interact.performed -= OnInteractPerformed; 
            input_handler.Player.Interact.performed += OnInteractPerformed;
        }

        private void OnInteractPerformed(InputAction.CallbackContext ctx)
        {
            if (active_player != null) active_player.Interact(ctx);
        }

        public void OnItemPickedUp()
        {
            if (current_player_index < indicators.Length && indicators[current_player_index] != null)
            {
                indicators[current_player_index].SetActive(true);
            }
        }

        public void OnPlayerLocked()
        {
            input_handler.Player.Interact.performed -= OnInteractPerformed;
            active_player.SetActiveState(false); // Disable the one that just finished

            ActivateTurn(current_player_index + 1);
        }

        void Update()
        {
            if (active_player == null) return;

            // Ensure your Input Action Asset has a Map called "Player" and Action called "Move"
            Vector2 move_value = input_handler.Player.Move.ReadValue<Vector2>();
            active_player.MovePlayer(move_value);
        }

        private void OnDestroy()
        {
            if (input_handler != null) input_handler.Disable();
        }
    }